server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource_mgmt
    username: root
    password: QIUHEchamygn1996@
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  application:
    name: "resource-service"

logging:
  level:
    org:
      springframework: ERROR

